- name: Provision db servers
  hosts: db-servers
  become: yes
  tasks:
    - name: Fail if "mysql_root_password" is undefined
      ansible.builtin.fail: msg="For security reasons, the MySQL root password should be passed as a parameter when running the playbook"
      when: mysql_root_password is undefined

    - name: Fail if "mysql_aplication_password" is undefined
      ansible.builtin.fail: msg="For security reasons, the MySQL application password should be passed as a parameter when running the playbook"
      when: mysql_aplication_password is undefined

    - name: Install MySQL server
      apt:
       update_cache: true
       name: mysql-server
       state: latest

    - name: Start the MySQL service
      service: 
        name: mysql
        state: started
        enabled: yes
    
    - name: Install pip
      apt:
       name: python3-pip
       state: latest

    - name: Make sure pymysql is present
      pip:
        name: pymysql
    
    # 'localhost' needs to be the last item for idempotency, see
    # http://ansible.cc/docs/modules.html#mysql-user
    - name: update mysql root password for all root accounts
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
      with_items:
        - 127.0.0.1
        - localhost

    - name: copy .my.cnf file with root password credentials
      template: src=templates/mysql_my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

    - name: delete anonymous MySQL server user for localhost
      mysql_user: 
        user: ""
        state: "absent"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: remove the MySQL test database
      mysql_db:
        db: test
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: create the application MySQL database
      mysql_db :
        db: books
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: create application MySQL user for localhost
      mysql_user:
        user: books
        host: "{{ item }}"
        password: "{{ mysql_aplication_password }}"
        priv: 'books.*:ALL'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      with_items:
        - 127.0.0.1
        - localhost
